// Code generated by protoc-gen-go-mesh-gen. DO NOT EDIT.

package test

import (
	grpc "google.golang.org/grpc"
	_ "google.golang.org/grpc/xds"
	os "os"
	sync "sync"
	grpc1 "test/grpc"
)

var _MyServiceOnce = new(sync.Once)
var _MyServiceclient MyServiceClient

func GetMyServiceClient() MyServiceClient {
	var host = "localhost"
	var scheme string
	if os.Getenv("GRPC_XDS_BOOTSTRAP") != "" {
		scheme = "xds:///"
		host = "myservice-grpc"
	}

	_MyServiceOnce.Do(func() {
		dial, err := grpc.Dial(scheme+host+":8080",
			grpc1.GetDialOptions("MyService")...,
		)
		if err != nil {
			_MyServiceOnce = new(sync.Once)
			panic(err)
		}
		_MyServiceclient = NewMyServiceClient(dial)
	})
	return _MyServiceclient
}
